version: '3'
services:
  youtube-scraper:
    build:
      context: .
      dockerfile: scraper.Dockerfile
    env_file:
      - .env
    working_dir: /yt
    command: ["python", "youtube_scraper"]

  rabbitmq:
    image: "rabbitmq:3.9-management"
    ports:
      - "5672:5672"
      - "15672:15672"
